build:
  binary: task
  main: ./cmd/task
  goos:
    - windows
    - darwin
    - linux
    - freebsd
  goarch:
    - amd64
    - s390x
  goarm:
    - '6'
  ignore:
    - goos: darwin
      goarch: '386'
  env:
    - CGO_ENABLED=0
  mod_timestamp: '{{ .CommitTimestamp }}'
  flags:
    - -trimpath
  ldflags:
    - -s -w # Don't set main.version.

gomod:
  proxy: false

archives:
  - name_template: "{{.Binary}}_{{.Os}}_{{.Arch}}"
    files:
      - README.md
      - LICENSE
      - completion/**/*
    format_overrides:
      - goos: windows
        format: zip

release:
  draft: true

snapshot:
  name_template: "{{.Tag}}"

checksum:
  name_template: "task_checksums.txt"

nfpms:
  - vendor: Task
    homepage: https://taskfile.dev
    maintainer: Andrey Nering <andrey@nering.com.br>
    description: Simple task runner written in Go
    license: MIT
    conflicts:
      - taskwarrior
    formats:
      - deb
      - rpm
    file_name_template: "{{.ProjectName}}_{{.Os}}_{{.Arch}}"
    contents:
      - src: completion/bash/task.bash
        dst: /etc/bash_completion.d/task
      - src: completion/fish/task.fish
        dst: /usr/share/fish/completions/task.fish
      - src: completion/zsh/_task
        dst: /usr/local/share/zsh/site-functions/_task

